env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
rules:
  'eol-last':
    - error
    - always
  'no-empty': ['error', { 'allowEmptyCatch': true }]
  'react/react-in-jsx-scope': 'off'
