vars:
  PRODUCT_NAME:
    default: Socious Wallet
  DISPLAY_NAME:
    default: Socious Wallet
  VERSION:
    default: 1.6.11
  ANDROID_VERSION_CODE:
    default: 3
  ANDROID_PACKAGE_NAME:
    default: socious.wallet.app
  ANDROID_KEY_STORE_LOCATION:
    default: ./android/build-release.keystore
  ANDROID_KEY_STORE_PASSWORD:
    default: Password
  ANDROID_KEY_ALIAS:
    default: key_number_one
  ANDROID_KEY_PASSWORD:
    default: Password
  IOS_BUILD_NUMBER:
    default: 39
  IOS_BUNDLE_ID:
    default: socious.mobile-wallet.app
  IOS_DEVELOPMENT_TEAM_ID:
    default: 596H9K48FY
  BASE_DEEPLINKING_URL:
    default: wallet.socious.io

platforms:
  ios:
    targets:
      App:
        bundleId: $IOS_BUNDLE_ID
        version: $VERSION
        buildNumber: $IOS_BUILD_NUMBER
        productName: $PRODUCT_NAME
        displayName: $DISPLAY_NAME

        buildSettings:
          DEVELOPMENT_TEAM: $IOS_DEVELOPMENT_TEAM_ID
          TARGETED_DEVICE_FAMILY: 1 #1: iPhone ,2:iPhone&iPad, 3:iPad
          CODE_SIGN_STYLE: Manual
          CODE_SIGN_IDENTITY: iPhone Distribution

        plist:
          replace: false
          entries:
            - ITSAppUsesNonExemptEncryption: false
            - NSCameraUsageDescription: Socious Wallet requires access to your camera to capture facial images for identity verification. This process helps to ensure that you are the rightful owner of the account and prevents unauthorized access. For example, your face data will be matched with your provided ID documents to confirm your identity.
            - UIFileSharingEnabled: true
            - LSSupportsOpeningDocumentsInPlace: true
            - NSDocumentsFolderUsageDescription: Socious Wallet needs access to your Documents folder to save files for secure storage and sharing.

        entitlements:
          replace: true
          entries:
            - com.apple.developer.associated-domains: ['applinks:$BASE_DEEPLINKING_URL']

  android:
    packageName: $ANDROID_PACKAGE_NAME
    versionName: $VERSION
    versionCode: $ANDROID_VERSION_CODE

    gradle:
      - file: app/build.gradle # Removing buildTypes
        target:
          android:
            buildTypes:
        replace:
          '': ''
      - file: app/build.gradle
        target:
          android:
        insert: |
          signingConfigs {
            release {
              // You need to specify either an absolute path or include the
              // keystore file in the same directory as the build.gradle file.
              storeFile file("$ANDROID_KEY_STORE_LOCATION")
              storePassword "$ANDROID_KEY_STORE_PASSWORD"
              keyAlias "$ANDROID_KEY_ALIAS"
              keyPassword "$ANDROID_KEY_PASSWORD"
            }
          }
      - file: app/build.gradle
        target:
          android:
        insert: |
          buildTypes {
            release {
              minifyEnabled false
              proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
              signingConfig signingConfigs.release
            }
          }
