vars:
  PRODUCT_NAME:
    default: Socious Wallet
  DISPLAY_NAME:
    default: Socious Wallet
  VERSION:
    default: 1.0.1
  ANDROID_VERSION_CODE:
    default: 3
  ANDROID_PACKAGE_NAME:
    default: socious.wallet.app
  ANDROID_KEY_STORE_LOCATION:
    default: ./android/build-release.keystore
  ANDROID_KEY_STORE_PASSWORD:
    default: Password
  ANDROID_KEY_ALIAS:
    default: key_number_one
  ANDROID_KEY_PASSWORD:
    default: Password
  IOS_BUILD_NUMBER:
    default: 1
  IOS_BUNDLE_ID:
    default: socious.wallet-mobile.app
  IOS_DEVELOPMENT_TEAM_ID:
    default: 596H9K48FY

platforms:
  ios:
    targets:
      App:
        bundleId: $IOS_BUNDLE_ID
        version: $VERSION
        buildNumber: $IOS_BUILD_NUMBER
        productName: $PRODUCT_NAME
        displayName: $DISPLAY_NAME

        buildSettings:
          DEVELOPMENT_TEAM: $IOS_DEVELOPMENT_TEAM_ID
          TARGETED_DEVICE_FAMILY: 1 #1: iPhone ,2:iPhone&iPad, 3:iPad
          CODE_SIGN_STYLE: Manual

        plist:
          replace: false
          entries:
            - NSCameraUsageDescription: We need access to your camera

  android:
    packageName: $ANDROID_PACKAGE_NAME
    versionName: $VERSION
    versionCode: $ANDROID_VERSION_CODE

    manifest:
      - file: AndroidManifest.xml
        target: manifest
        inject: |
          <uses-permission android:name="android.permission.CAMERA" />
    gradle:
      - file: app/build.gradle # Removing buildTypes
        target:
          android:
            buildTypes:
        replace:
          '': ''
      - file: app/build.gradle
        target:
          android:
        insert: |
          signingConfigs {
            release {
              // You need to specify either an absolute path or include the
              // keystore file in the same directory as the build.gradle file.
              storeFile file("$ANDROID_KEY_STORE_LOCATION")
              storePassword "$ANDROID_KEY_STORE_PASSWORD"
              keyAlias "$ANDROID_KEY_ALIAS"
              keyPassword "$ANDROID_KEY_PASSWORD"
            }
          }
      - file: app/build.gradle
        target:
          android:
        insert: |
          buildTypes {
            release {
              minifyEnabled false
              proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
              signingConfig signingConfigs.release
            }
          }








          
